version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "CargoSense/dx-reviewers"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      eslint-core:
        - "@eslint/compat"
        - "@eslint/js"
        - "eslint"
    reviewers:
      - "CargoSense/front-end-reviewers"
